#!/usr/bin/env python3
# Backwards compatibility script to port python HDWX products to GEMPAK HDWX viewer
# Created 2 Feburary 2022 by Sam Gardner <stgardner4@tamu.edu>

import sys
import json
from os import path, listdir
from shutil import rmtree, copyfile
from pathlib import Path
import imageio

def generatePlaceholderImage():
    from matplotlib import pyplot as plt
    from cartopy import crs as ccrs
    from cartopy import feature as cfeat
    from matplotlib import image as mpimage
    fig = plt.figure()
    ax = plt.axes(projection=ccrs.epsg(3857))
    ax.set_extent([-130, -60, 20, 50], crs=ccrs.PlateCarree())
    ax.add_feature(cfeat.STATES.with_scale("50m"), linewidth=0.5)
    ax.add_feature(cfeat.COASTLINE.with_scale("50m"), linewidth=0.5)
    ax.text(-98.35, 39.5, "Product generation in progress.\nPlease stand by...", horizontalalignment="center", verticalalignment="center", fontsize=36, transform=ccrs.PlateCarree())
    # ax.set_position([ax.get_position().x0, .12, ax.get_position().width, ax.get_position().height])
    if path.exists(path.join(sys.argv[1], "assets", "atmoLogo.png")):
        lax = fig.add_axes([(.99-(ax.get_position().width/3)),0,(ax.get_position().width/3),.1])
        lax.set_aspect(2821/11071)
        lax.axis("off")
        plt.setp(lax.spines.values(), visible=False)
        atmoLogo = mpimage.imread(path.join(sys.argv[1], "assets", "atmoLogo.png"))
        lax.imshow(atmoLogo)
    px = 1/plt.rcParams["figure.dpi"]
    fig.set_size_inches(1920*px, 1080*px)
    fig.savefig("placeholder.gif")

if __name__ == "__main__":
    # Get path to hdwx root
    basePath = path.abspath(path.dirname(__file__))
    # Get requested submodule path from command-line argument
    submodulePath = sys.argv[1]
    # Get the requested metadata dir, ./<submodule>/output/metadata/
    metadataDir = path.join(basePath, submodulePath, "output", "metadata")
    # List all of the registered products generated by this submodule
    generatedProductIDs = [jsonFileName.replace(".json", "") for jsonFileName in sorted(listdir(metadataDir)) if ".json" in jsonFileName]
    # Now we iterate over all of the products generated by this submodule
    for productID in generatedProductIDs:
        # Get all available productRun json files
        productRunsDirPath = path.join(metadataDir, "products", productID)
        productRunsJsonPaths = [path.join(productRunsDirPath, runJsonFileName) for runJsonFileName in sorted(listdir(productRunsDirPath))]
        # If there are any runs available...
        if len(productRunsJsonPaths) > 0:    
            # Create empty list as container for the paths to the images that will go in the "backport" directory
            framesToCopy = list()
            # Load product metadata
            productJsonPath = path.join(metadataDir, productID+".json")
            if path.exists(productJsonPath):
                with open(productJsonPath, "r") as jsonRead:
                    productMetadata = json.load(jsonRead)
                # If we're not dealing with png images, none of this will work
                if productMetadata["fileExtension"] == "png":
                    # GIS products dont need to be made compatibile with the non-GIS product viewer
                    if productMetadata["isGIS"] == False:
                        # get product path
                        productPath = productMetadata["productPath"]
                        # Check if the product wants to have a single run loaded or backfill across multiple runs
                        if productMetadata["displayFrames"] <= 0:
                            # If the displayFrames is 0 (or less... although it shouldn't ever be... unless I think of some creative way to use that in the future)
                            # then we want entire the latest run, and only frames from the latest run
                            latestRunPath = productRunsJsonPaths[-1]
                            # Load metadata from latest run
                            with open(latestRunPath, "r") as jsonRead:
                                latestRunMetadata = json.load(jsonRead)
                            # get suffix for the latest run
                            runPathExtension = latestRunMetadata["pathExtension"]
                            # Add all available frames to the list of frames to copy
                            [framesToCopy.append(path.join(path.dirname(metadataDir), productPath, runPathExtension, productFrame["filename"])) for productFrame in latestRunMetadata["productFrames"]]
                            # But since all the available frames may not necessarily fill all the requested frames, we need to do something with the excess...
                            if len(framesToCopy) < latestRunMetadata["totalFrameCount"]:
                                # Use a placeholder image for frames after completion but less than the expected number of frames in the run
                                shouldUsePlaceHolder = True
                                # If the aforementioned placeholder image doesn't exist yet, generated it now
                                if not path.exists(path.join(basePath, "placeholder.gif")):
                                    generatePlaceholderImage()
                                # Fill the remaining frames with the path to the placeholder image
                                [framesToCopy.append(path.join(basePath, "placeholder.gif")) for _ in range(len(framesToCopy), latestRunMetadata["totalFrameCount"])]
                        else:
                            # If display frames is not 0, then we want to display that exact number of frames. If the latest run contains less than this value,
                            # then we want to backfill from previous runs.
                            # This is of course a "you just indexed out of bounds on that array" error waiting to happen, so careful tracking is needed
                            runsBack = 0
                            idxToApnd = 0
                            while len(framesToCopy) < productMetadata["displayFrames"]:
                                idxToApnd = idxToApnd - 1
                                if idxToApnd < 0:
                                    # We're going back one run
                                    runsBack = runsBack + 1
                                    # Check to see that we actually have another run to read in
                                    if (len(productRunsJsonPaths) - runsBack) >= 0:
                                        # Read in the run data from that index
                                        requestedRunPath = productRunsJsonPaths[-runsBack]
                                        with open(requestedRunPath, "r") as jsonRead:
                                            runMetadata = json.load(jsonRead)
                                        # We're about to start adding frames in reverse order, from the last frame to the first.
                                        # We need to know what index to start at (last), which is the length minus 1
                                        idxToApnd = len(runMetadata["productFrames"]) - 1
                                        # Update runPathExtension
                                        runPathExtension = runMetadata["pathExtension"]
                                    else:
                                        break
                                framesToCopy.append(path.join(path.dirname(metadataDir), productPath, runPathExtension, runMetadata["productFrames"][idxToApnd]["filename"]))
                            # Since we've just built this whole list backwards...
                            framesToCopy.reverse()
                            # If there aren't enough frames to fill the display frames, then repeat the list as many times as possible.
                            # This isn't perfect, as if you have 10 frames available, and "displayFrames" is 15, you'll get one and a half loops,
                            # but the alternative is just leaving the user on a blank screen which is not good UX
                            a = 0
                            while len(framesToCopy) < productMetadata["displayFrames"]:
                                framesToCopy.append(path.join(path.dirname(metadataDir), productPath, "latest", "frame"+str(a)+".gif"))
                                a = a + 1
                        # Get path to target directory
                        targetPath = path.join(path.dirname(metadataDir), productPath, "latest")
                        # Now, delete the target directory and re-create it (to empty it)
                        if path.exists(targetPath):
                            rmtree(targetPath)
                        Path(targetPath).mkdir(parents=True, exist_ok=True)
                        # Loop through the list of the source images
                        for i in range(0, len(framesToCopy)):
                            # Get the source and target file paths
                            sourceFile = framesToCopy[i]
                            targetFile = path.join(targetPath, "frame"+str(i)+".gif")
                            # if the source is already a gif, all we need to do is copy it
                            if ".gif" in sourceFile:
                                copyfile(sourceFile, targetFile)
                            # Otherwise, we have to convert the image to a GIF first, then write out
                            else:
                                with imageio.get_writer(targetFile, mode="I") as writer:
                                    imageToConvert = imageio.imread(sourceFile)
                                    writer.append_data(imageToConvert)
                        # Generate a thumbnail from the first image
                        if path.exists(path.join(targetPath, "frame0.gif")):
                            copyfile(path.join(targetPath, "frame0.gif"), path.join(targetPath, "thumb.gif"))